name: "Build Docs"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
    - uses: EndBug/add-and-commit@v9 
      with:
        add: 'build'

